apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: joao-test
data:
  PORT: '8080'
  ENVVAR: 'Staging'

---

apiVersion: v1
kind: Service
metadata:
  namespace: joao-test
  name: joao-test
spec:
  selector:
    app: joao-test
  ports:
    - port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: joao-test
  namespace: joao-test
  labels:
    app: joao-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joao-test
  template:
    metadata:
      name: joao-test
      labels:
        app: joao-test
    spec:
      imagePullSecrets:
      - name: acr-login
      containers:
      - name: joao-test
        image: inf1lightstreameus2.azurecr.io/joao-test
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: PORT
        - name: ENVVAR 
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ENVVAR